# Generated by Django 5.0 on 2023-12-21 05:08

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['txt', 'csv'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=250)),
                ('run_time', models.FloatField()),
                ('screenshot', models.FilePathField(null=True, path='STA_REST_API/screenshots')),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=200, null=True), size=None)),
                ('webpage_size', models.FloatField(null=True)),
                ('test_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.testgroupmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
