# Generated by Django 5.0 on 2023-12-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_testresultmodel_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresultmodel',
            name='screenshot',
            field=models.FilePathField(null=True, path='/screenshots/'),
        ),
    ]
