# Generated by Django 5.0 on 2023-12-21 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_testresultmodel_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresultmodel',
            name='screenshot',
        ),
    ]
