# Generated by Django 5.0 on 2023-12-21 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_testresultmodel_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresultmodel',
            name='run_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
