# Generated by Django 5.0 on 2023-12-22 20:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_testresultmodel_run_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroupmodel',
            name='file',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=200, null=True), size=None),
        ),
    ]
