# Generated by Django 5.0 on 2023-12-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_testgroupmodel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testgroupmodel',
            old_name='file',
            new_name='file_data',
        ),
    ]
